package com.github.vedenin.useful_links;

import java.util.HashMap;
import java.util.HashSet;
import java.util.Map;
import java.util.Set;

/**
 * Global constants
 *
 * Created by vvedenin on 5/12/2016.
 */
public final class Constants {


    public static final String GIT_HUB_URL = "github.com/";
    public static final String GIT_HUB_URL_FULL = "https://" + GIT_HUB_URL;
    public static final String USER_AGENT = "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/33.0.1750.152 Safari/537.36";

    private Constants() {}

    public static final Map<String, String> LANGUAGES = new HashMap<>(); // key, name - All programming languages from github
    public static final Map<String, String> POPULAR_LANGUAGES = new HashMap<>(); // key, name - popular languages from github


    static {
        POPULAR_LANGUAGES.put("ActionScript", "ActionScript");
        POPULAR_LANGUAGES.put("C", "C");
        POPULAR_LANGUAGES.put("C#", "C#");
        POPULAR_LANGUAGES.put("C++", "C++");
        POPULAR_LANGUAGES.put("Clojure", "Clojure");
        POPULAR_LANGUAGES.put("CoffeeScript", "CoffeeScript");
        POPULAR_LANGUAGES.put("CSS", "CSS");
        POPULAR_LANGUAGES.put("Go", "Go");
        POPULAR_LANGUAGES.put("Haskell", "Haskell");
        POPULAR_LANGUAGES.put("HTML", "HTML");
        POPULAR_LANGUAGES.put("Java", "Java");
        POPULAR_LANGUAGES.put("JavaScript", "JavaScript");
        POPULAR_LANGUAGES.put("Lua", "Lua");
        POPULAR_LANGUAGES.put("Matlab", "Matlab");
        POPULAR_LANGUAGES.put("Objective-C", "Objective-C");
        POPULAR_LANGUAGES.put("Perl", "Perl");
        POPULAR_LANGUAGES.put("PHP", "PHP");
        POPULAR_LANGUAGES.put("Python", "Python");
        POPULAR_LANGUAGES.put("R", "R");
        POPULAR_LANGUAGES.put("Ruby", "Ruby");
        POPULAR_LANGUAGES.put("Scala", "Scala");
        POPULAR_LANGUAGES.put("Shell", "Shell");
        POPULAR_LANGUAGES.put("Swift", "Swift");
        POPULAR_LANGUAGES.put("TeX", "TeX");
        POPULAR_LANGUAGES.put("VimL", "VimL");
        POPULAR_LANGUAGES.put("Elixir", "Elixir");
        POPULAR_LANGUAGES.put("Rust", "Rust");
        POPULAR_LANGUAGES.put("PureScript", "PureScript");
        POPULAR_LANGUAGES.put("Elm", "Elm");
        POPULAR_LANGUAGES.put("Erlang", "Erlang");
        POPULAR_LANGUAGES.put("Julia", "Julia");
        POPULAR_LANGUAGES.put("D", "D");
        POPULAR_LANGUAGES.put("Common Lisp", "Common Lisp");
        POPULAR_LANGUAGES.put("Groovy", "Groovy");
        POPULAR_LANGUAGES.put("Dart", "Dart");
        POPULAR_LANGUAGES.put("Kotlin", "Kotlin");
        POPULAR_LANGUAGES.put("OCaml", "OCaml");
        POPULAR_LANGUAGES.put("ColdFusion", "ColdFusion");
        POPULAR_LANGUAGES.put("FORTRAN", "FORTRAN");
        POPULAR_LANGUAGES.put("AutoHotkey", "AutoHotkey");
        POPULAR_LANGUAGES.put("AutoIt", "AutoIt");
        POPULAR_LANGUAGES.put("Crystal", "Crystal");
        POPULAR_LANGUAGES.put("TypeScript", "TypeScript");
    }

    static {
        LANGUAGES.put("Assembly", "Assembly");
        LANGUAGES.put("AutoIt", "AutoIt");
        LANGUAGES.put("AutoHotkey", "AutoHotkey");
        LANGUAGES.put("ActionScript", "ActionScript");
        LANGUAGES.put("C", "C");
        LANGUAGES.put("C#", "C#");
        LANGUAGES.put("C++", "C++");
        LANGUAGES.put("Clojure", "Clojure");
        LANGUAGES.put("CoffeeScript", "CoffeeScript");
        LANGUAGES.put("CSS", "CSS");
        LANGUAGES.put("Go", "Go");
        LANGUAGES.put("Haskell", "Haskell");
        LANGUAGES.put("HTML", "HTML");
        LANGUAGES.put("Java", "Java");
        LANGUAGES.put("JavaScript", "JavaScript");
        LANGUAGES.put("Lua", "Lua");
        LANGUAGES.put("Matlab", "Matlab");
        LANGUAGES.put("Objective-C", "Objective-C");
        LANGUAGES.put("Perl", "Perl");
        LANGUAGES.put("PHP", "PHP");
        LANGUAGES.put("Python", "Python");
        LANGUAGES.put("R", "R");
        LANGUAGES.put("Ruby", "Ruby");
        LANGUAGES.put("Scala", "Scala");
        LANGUAGES.put("Shell", "Shell");
        LANGUAGES.put("Swift", "Swift");
        LANGUAGES.put("TeX", "TeX");
        LANGUAGES.put("VimL", "VimL");
        LANGUAGES.put("ABAP", "ABAP");
        LANGUAGES.put("Ada", "Ada");
        LANGUAGES.put("Agda", "Agda");
        LANGUAGES.put("AGS Script", "AGS Script");
        LANGUAGES.put("Alloy", "Alloy");
        LANGUAGES.put("Alpine Abuild", "Alpine Abuild");
        LANGUAGES.put("AMPL", "AMPL");
        LANGUAGES.put("Ant Build System", "Ant Build System");
        LANGUAGES.put("ANTLR", "ANTLR");
        LANGUAGES.put("ApacheConf", "ApacheConf");
        LANGUAGES.put("Apex", "Apex");
        LANGUAGES.put("API Blueprint", "API Blueprint");
        LANGUAGES.put("APL", "APL");
        LANGUAGES.put("AppleScript", "AppleScript");
        LANGUAGES.put("Arc", "Arc");
        LANGUAGES.put("Arduino", "Arduino");
        LANGUAGES.put("AsciiDoc", "AsciiDoc");
        LANGUAGES.put("ASP", "ASP");
        LANGUAGES.put("AspectJ", "AspectJ");
        LANGUAGES.put("ATS", "ATS");
        LANGUAGES.put("Augeas", "Augeas");
        LANGUAGES.put("Awk", "Awk");
        LANGUAGES.put("Batchfile", "Batchfile");
        LANGUAGES.put("Befunge", "Befunge");
        LANGUAGES.put("Bison", "Bison");
        LANGUAGES.put("BitBake", "BitBake");
        LANGUAGES.put("BlitzBasic", "BlitzBasic");
        LANGUAGES.put("BlitzMax", "BlitzMax");
        LANGUAGES.put("Bluespec", "Bluespec");
        LANGUAGES.put("Boo", "Boo");
        LANGUAGES.put("Brainfuck", "Brainfuck");
        LANGUAGES.put("Brightscript", "Brightscript");
        LANGUAGES.put("Bro", "Bro");
        LANGUAGES.put("C-ObjDump", "C-ObjDump");
        LANGUAGES.put("C2hs Haskell", "C2hs Haskell");
        LANGUAGES.put("Cap&#39;n Proto", "Cap&#39;n Proto");
        LANGUAGES.put("CartoCSS", "CartoCSS");
        LANGUAGES.put("Ceylon", "Ceylon");
        LANGUAGES.put("Chapel", "Chapel");
        LANGUAGES.put("Charity", "Charity");
        LANGUAGES.put("ChucK", "ChucK");
        LANGUAGES.put("Cirru", "Cirru");
        LANGUAGES.put("Clarion", "Clarion");
        LANGUAGES.put("Clean", "Clean");
        LANGUAGES.put("Click", "Click");
        LANGUAGES.put("CLIPS", "CLIPS");
        LANGUAGES.put("CMake", "CMake");
        LANGUAGES.put("COBOL", "COBOL");
        LANGUAGES.put("ColdFusion", "ColdFusion");
        LANGUAGES.put("ColdFusion CFC", "ColdFusion CFC");
        LANGUAGES.put("COLLADA", "COLLADA");
        LANGUAGES.put("Common Lisp", "Common Lisp");
        LANGUAGES.put("Component Pascal", "Component Pascal");
        LANGUAGES.put("Cool", "Cool");
        LANGUAGES.put("Coq", "Coq");
        LANGUAGES.put("Cpp-ObjDump", "Cpp-ObjDump");
        LANGUAGES.put("Creole", "Creole");
        LANGUAGES.put("Crystal", "Crystal");
        LANGUAGES.put("Csound", "Csound");
        LANGUAGES.put("Csound Document", "Csound Document");
        LANGUAGES.put("Csound Score", "Csound Score");
        LANGUAGES.put("CSV", "CSV");
        LANGUAGES.put("Cucumber", "Cucumber");
        LANGUAGES.put("Cuda", "Cuda");
        LANGUAGES.put("Cycript", "Cycript");
        LANGUAGES.put("Cython", "Cython");
        LANGUAGES.put("D", "D");
        LANGUAGES.put("D-ObjDump", "D-ObjDump");
        LANGUAGES.put("Darcs Patch", "Darcs Patch");
        LANGUAGES.put("Dart", "Dart");
        LANGUAGES.put("desktop", "desktop");
        LANGUAGES.put("Diff", "Diff");
        LANGUAGES.put("DIGITAL Command Language", "DIGITAL Command Language");
        LANGUAGES.put("DM", "DM");
        LANGUAGES.put("DNS Zone", "DNS Zone");
        LANGUAGES.put("Dockerfile", "Dockerfile");
        LANGUAGES.put("Dogescript", "Dogescript");
        LANGUAGES.put("DTrace", "DTrace");
        LANGUAGES.put("Dylan", "Dylan");
        LANGUAGES.put("E", "E");
        LANGUAGES.put("Eagle", "Eagle");
        LANGUAGES.put("eC", "eC");
        LANGUAGES.put("Ecere Projects", "Ecere Projects");
        LANGUAGES.put("ECL", "ECL");
        LANGUAGES.put("ECLiPSe", "ECLiPSe");
        LANGUAGES.put("edn", "edn");
        LANGUAGES.put("Eiffel", "Eiffel");
        LANGUAGES.put("EJS", "EJS");
        LANGUAGES.put("Elixir", "Elixir");
        LANGUAGES.put("Elm", "Elm");
        LANGUAGES.put("Emacs Lisp", "Emacs Lisp");
        LANGUAGES.put("EmberScript", "EmberScript");
        LANGUAGES.put("Erlang", "Erlang");
        LANGUAGES.put("F#", "F#");
        LANGUAGES.put("Factor", "Factor");
        LANGUAGES.put("Fancy", "Fancy");
        LANGUAGES.put("Fantom", "Fantom");
        LANGUAGES.put("Filterscript", "Filterscript");
        LANGUAGES.put("fish", "fish");
        LANGUAGES.put("FLUX", "FLUX");
        LANGUAGES.put("Formatted", "Formatted");
        LANGUAGES.put("Forth", "Forth");
        LANGUAGES.put("FORTRAN", "FORTRAN");
        LANGUAGES.put("FreeMarker", "FreeMarker");
        LANGUAGES.put("Frege", "Frege");
        LANGUAGES.put("G-code", "G-code");
        LANGUAGES.put("Game Maker Language", "Game Maker Language");
        LANGUAGES.put("GAMS", "GAMS");
        LANGUAGES.put("GAP", "GAP");
        LANGUAGES.put("GAS", "GAS");
        LANGUAGES.put("GDScript", "GDScript");
        LANGUAGES.put("Genshi", "Genshi");
        LANGUAGES.put("Gentoo Ebuild", "Gentoo Ebuild");
        LANGUAGES.put("Gentoo Eclass", "Gentoo Eclass");
        LANGUAGES.put("Gettext Catalog", "Gettext Catalog");
        LANGUAGES.put("GLSL", "GLSL");
        LANGUAGES.put("Glyph", "Glyph");
        LANGUAGES.put("Gnuplot", "Gnuplot");
        LANGUAGES.put("Golo", "Golo");
        LANGUAGES.put("Gosu", "Gosu");
        LANGUAGES.put("Grace", "Grace");
        LANGUAGES.put("Gradle", "Gradle");
        LANGUAGES.put("Grammatical Framework", "Grammatical Framework");
        LANGUAGES.put("Graph Modeling Language", "Graph Modeling Language");
        LANGUAGES.put("GraphQL", "GraphQL");
        LANGUAGES.put("Graphviz (DOT)", "Graphviz (DOT)");
        LANGUAGES.put("Groff", "Groff");
        LANGUAGES.put("Groovy", "Groovy");
        LANGUAGES.put("Groovy Server Pages", "Groovy Server Pages");
        LANGUAGES.put("Hack", "Hack");
        LANGUAGES.put("Haml", "Haml");
        LANGUAGES.put("Handlebars", "Handlebars");
        LANGUAGES.put("Harbour", "Harbour");
        LANGUAGES.put("Haxe", "Haxe");
        LANGUAGES.put("HCL", "HCL");
        LANGUAGES.put("HLSL", "HLSL");
        LANGUAGES.put("HTML+Django", "HTML+Django");
        LANGUAGES.put("HTML+ECR", "HTML+ECR");
        LANGUAGES.put("HTML+EEX", "HTML+EEX");
        LANGUAGES.put("HTML+ERB", "HTML+ERB");
        LANGUAGES.put("HTML+PHP", "HTML+PHP");
        LANGUAGES.put("HTTP", "HTTP");
        LANGUAGES.put("Hy", "Hy");
        LANGUAGES.put("HyPhy", "HyPhy");
        LANGUAGES.put("IDL", "IDL");
        LANGUAGES.put("Idris", "Idris");
        LANGUAGES.put("IGOR Pro", "IGOR Pro");
        LANGUAGES.put("Inform 7", "Inform 7");
        LANGUAGES.put("INI", "INI");
        LANGUAGES.put("Inno Setup", "Inno Setup");
        LANGUAGES.put("Io", "Io");
        LANGUAGES.put("Ioke", "Ioke");
        LANGUAGES.put("IRC log", "IRC log");
        LANGUAGES.put("Isabelle", "Isabelle");
        LANGUAGES.put("Isabelle ROOT", "Isabelle ROOT");
        LANGUAGES.put("J", "J");
        LANGUAGES.put("Jade", "Jade");
        LANGUAGES.put("Jasmin", "Jasmin");
        LANGUAGES.put("Java Server Pages", "Java Server Pages");
        LANGUAGES.put("JFlex", "JFlex");
        LANGUAGES.put("JSON", "JSON");
        LANGUAGES.put("JSON5", "JSON5");
        LANGUAGES.put("JSONiq", "JSONiq");
        LANGUAGES.put("JSONLD", "JSONLD");
        LANGUAGES.put("JSX", "JSX");
        LANGUAGES.put("Julia", "Julia");
        LANGUAGES.put("Jupyter Notebook", "Jupyter Notebook");
        LANGUAGES.put("KiCad", "KiCad");
        LANGUAGES.put("Kit", "Kit");
        LANGUAGES.put("Kotlin", "Kotlin");
        LANGUAGES.put("KRL", "KRL");
        LANGUAGES.put("LabVIEW", "LabVIEW");
        LANGUAGES.put("Lasso", "Lasso");
        LANGUAGES.put("Latte", "Latte");
        LANGUAGES.put("Lean", "Lean");
        LANGUAGES.put("Less", "Less");
        LANGUAGES.put("Lex", "Lex");
        LANGUAGES.put("LFE", "LFE");
        LANGUAGES.put("LilyPond", "LilyPond");
        LANGUAGES.put("Limbo", "Limbo");
        LANGUAGES.put("Linker Script", "Linker Script");
        LANGUAGES.put("Linux Kernel Module", "Linux Kernel Module");
        LANGUAGES.put("Liquid", "Liquid");
        LANGUAGES.put("Literate Agda", "Literate Agda");
        LANGUAGES.put("Literate CoffeeScript", "Literate CoffeeScript");
        LANGUAGES.put("Literate Haskell", "Literate Haskell");
        LANGUAGES.put("LiveScript", "LiveScript");
        LANGUAGES.put("LLVM", "LLVM");
        LANGUAGES.put("Logos", "Logos");
        LANGUAGES.put("Logtalk", "Logtalk");
        LANGUAGES.put("LOLCODE", "LOLCODE");
        LANGUAGES.put("LookML", "LookML");
        LANGUAGES.put("LoomScript", "LoomScript");
        LANGUAGES.put("LSL", "LSL");
        LANGUAGES.put("M", "M");
        LANGUAGES.put("M4", "M4");
        LANGUAGES.put("M4Sugar", "M4Sugar");
        LANGUAGES.put("Makefile", "Makefile");
        LANGUAGES.put("Mako", "Mako");
        LANGUAGES.put("Markdown", "Markdown");
        LANGUAGES.put("Mask", "Mask");
        LANGUAGES.put("Mathematica", "Mathematica");
        LANGUAGES.put("Maven POM", "Maven POM");
        LANGUAGES.put("Max", "Max");
        LANGUAGES.put("MAXScript", "MAXScript");
        LANGUAGES.put("MediaWiki", "MediaWiki");
        LANGUAGES.put("Mercury", "Mercury");
        LANGUAGES.put("Metal", "Metal");
        LANGUAGES.put("MiniD", "MiniD");
        LANGUAGES.put("Mirah", "Mirah");
        LANGUAGES.put("Modelica", "Modelica");
        LANGUAGES.put("Modula-2", "Modula-2");
        LANGUAGES.put("Module Management System", "Module Management System");
        LANGUAGES.put("Monkey", "Monkey");
        LANGUAGES.put("Moocode", "Moocode");
        LANGUAGES.put("MoonScript", "MoonScript");
        LANGUAGES.put("MTML", "MTML");
        LANGUAGES.put("MUF", "MUF");
        LANGUAGES.put("mupad", "mupad");
        LANGUAGES.put("Myghty", "Myghty");
        LANGUAGES.put("NCL", "NCL");
        LANGUAGES.put("Nemerle", "Nemerle");
        LANGUAGES.put("nesC", "nesC");
        LANGUAGES.put("NetLinx", "NetLinx");
        LANGUAGES.put("NetLinx+ERB", "NetLinx+ERB");
        LANGUAGES.put("NetLogo", "NetLogo");
        LANGUAGES.put("NewLisp", "NewLisp");
        LANGUAGES.put("Nginx", "Nginx");
        LANGUAGES.put("Nimrod", "Nimrod");
        LANGUAGES.put("Ninja", "Ninja");
        LANGUAGES.put("Nit", "Nit");
        LANGUAGES.put("Nix", "Nix");
        LANGUAGES.put("NL", "NL");
        LANGUAGES.put("NSIS", "NSIS");
        LANGUAGES.put("Nu", "Nu");
        LANGUAGES.put("NumPy", "NumPy");
        LANGUAGES.put("ObjDump", "ObjDump");
        LANGUAGES.put("Objective-C++", "Objective-C++");
        LANGUAGES.put("Objective-J", "Objective-J");
        LANGUAGES.put("OCaml", "OCaml");
        LANGUAGES.put("Omgrofl", "Omgrofl");
        LANGUAGES.put("ooc", "ooc");
        LANGUAGES.put("Opa", "Opa");
        LANGUAGES.put("Opal", "Opal");
        LANGUAGES.put("OpenCL", "OpenCL");
        LANGUAGES.put("OpenEdge ABL", "OpenEdge ABL");
        LANGUAGES.put("OpenRC runscript", "OpenRC runscript");
        LANGUAGES.put("OpenSCAD", "OpenSCAD");
        LANGUAGES.put("Org", "Org");
        LANGUAGES.put("Ox", "Ox");
        LANGUAGES.put("Oxygene", "Oxygene");
        LANGUAGES.put("Oz", "Oz");
        LANGUAGES.put("Pan", "Pan");
        LANGUAGES.put("Papyrus", "Papyrus");
        LANGUAGES.put("Parrot", "Parrot");
        LANGUAGES.put("Parrot Assembly", "Parrot Assembly");
        LANGUAGES.put("Parrot Internal Representation", "Parrot Internal Representation");
        LANGUAGES.put("Pascal", "Pascal");
        LANGUAGES.put("PAWN", "PAWN");
        LANGUAGES.put("Perl6", "Perl6");
        LANGUAGES.put("Pickle", "Pickle");
        LANGUAGES.put("PicoLisp", "PicoLisp");
        LANGUAGES.put("PigLatin", "PigLatin");
        LANGUAGES.put("Pike", "Pike");
        LANGUAGES.put("PLpgSQL", "PLpgSQL");
        LANGUAGES.put("PLSQL", "PLSQL");
        LANGUAGES.put("Pod", "Pod");
        LANGUAGES.put("PogoScript", "PogoScript");
        LANGUAGES.put("Pony", "Pony");
        LANGUAGES.put("PostScript", "PostScript");
        LANGUAGES.put("POV-Ray SDL", "POV-Ray SDL");
        LANGUAGES.put("PowerShell", "PowerShell");
        LANGUAGES.put("Processing", "Processing");
        LANGUAGES.put("Prolog", "Prolog");
        LANGUAGES.put("Propeller Spin", "Propeller Spin");
        LANGUAGES.put("Protocol Buffer", "Protocol Buffer");
        LANGUAGES.put("Public Key", "Public Key");
        LANGUAGES.put("Puppet", "Puppet");
        LANGUAGES.put("Pure Data", "Pure Data");
        LANGUAGES.put("PureBasic", "PureBasic");
        LANGUAGES.put("PureScript", "PureScript");
        LANGUAGES.put("Python traceback", "Python traceback");
        LANGUAGES.put("QMake", "QMake");
        LANGUAGES.put("QML", "QML");
        LANGUAGES.put("Racket", "Racket");
        LANGUAGES.put("Ragel in Ruby Host", "Ragel in Ruby Host");
        LANGUAGES.put("RAML", "RAML");
        LANGUAGES.put("Raw token data", "Raw token data");
        LANGUAGES.put("RDoc", "RDoc");
        LANGUAGES.put("REALbasic", "REALbasic");
        LANGUAGES.put("Rebol", "Rebol");
        LANGUAGES.put("Red", "Red");
        LANGUAGES.put("Redcode", "Redcode");
        LANGUAGES.put("Ren&#39;Py", "Ren&#39;Py");
        LANGUAGES.put("RenderScript", "RenderScript");
        LANGUAGES.put("reStructuredText", "reStructuredText");
        LANGUAGES.put("RHTML", "RHTML");
        LANGUAGES.put("RMarkdown", "RMarkdown");
        LANGUAGES.put("RobotFramework", "RobotFramework");
        LANGUAGES.put("Rouge", "Rouge");
        LANGUAGES.put("Rust", "Rust");
        LANGUAGES.put("Sage", "Sage");
        LANGUAGES.put("SaltStack", "SaltStack");
        LANGUAGES.put("SAS", "SAS");
        LANGUAGES.put("Sass", "Sass");
        LANGUAGES.put("Scaml", "Scaml");
        LANGUAGES.put("Scheme", "Scheme");
        LANGUAGES.put("Scilab", "Scilab");
        LANGUAGES.put("SCSS", "SCSS");
        LANGUAGES.put("Self", "Self");
        LANGUAGES.put("ShellSession", "ShellSession");
        LANGUAGES.put("Shen", "Shen");
        LANGUAGES.put("Slash", "Slash");
        LANGUAGES.put("Slim", "Slim");
        LANGUAGES.put("Smali", "Smali");
        LANGUAGES.put("Smalltalk", "Smalltalk");
        LANGUAGES.put("Smarty", "Smarty");
        LANGUAGES.put("SMT", "SMT");
        LANGUAGES.put("SourcePawn", "SourcePawn");
        LANGUAGES.put("SPARQL", "SPARQL");
        LANGUAGES.put("SQF", "SQF");
        LANGUAGES.put("SQL", "SQL");
        LANGUAGES.put("SQLPL", "SQLPL");
        LANGUAGES.put("Squirrel", "Squirrel");
        LANGUAGES.put("Stan", "Stan");
        LANGUAGES.put("Standard ML", "Standard ML");
        LANGUAGES.put("Stata", "Stata");
        LANGUAGES.put("STON", "STON");
        LANGUAGES.put("Stylus", "Stylus");
        LANGUAGES.put("SuperCollider", "SuperCollider");
        LANGUAGES.put("SVG", "SVG");
        LANGUAGES.put("SystemVerilog", "SystemVerilog");
        LANGUAGES.put("Tcl", "Tcl");
        LANGUAGES.put("Tcsh", "Tcsh");
        LANGUAGES.put("Tea", "Tea");
        LANGUAGES.put("Terra", "Terra");
        LANGUAGES.put("Text", "Text");
        LANGUAGES.put("Textile", "Textile");
        LANGUAGES.put("Thrift", "Thrift");
        LANGUAGES.put("TLA", "TLA");
        LANGUAGES.put("TOML", "TOML");
        LANGUAGES.put("Turing", "Turing");
        LANGUAGES.put("Turtle", "Turtle");
        LANGUAGES.put("Twig", "Twig");
        LANGUAGES.put("TXL", "TXL");
        LANGUAGES.put("TypeScript", "TypeScript");
        LANGUAGES.put("Unified Parallel C", "Unified Parallel C");
        LANGUAGES.put("Unity3D Asset", "Unity3D Asset");
        LANGUAGES.put("Uno", "Uno");
        LANGUAGES.put("UnrealScript", "UnrealScript");
        LANGUAGES.put("UrWeb", "UrWeb");
        LANGUAGES.put("Vala", "Vala");
        LANGUAGES.put("VCL", "VCL");
        LANGUAGES.put("Verilog", "Verilog");
        LANGUAGES.put("VHDL", "VHDL");
        LANGUAGES.put("Visual Basic", "Visual Basic");
        LANGUAGES.put("Volt", "Volt");
        LANGUAGES.put("Vue", "Vue");
        LANGUAGES.put("Wavefront Material", "Wavefront Material");
        LANGUAGES.put("Wavefront Object", "Wavefront Object");
        LANGUAGES.put("Web Ontology Language", "Web Ontology Language");
        LANGUAGES.put("WebIDL", "WebIDL");
        LANGUAGES.put("wisp", "wisp");
        LANGUAGES.put("World of Warcraft Addon Data", "World of Warcraft Addon Data");
        LANGUAGES.put("X10", "X10");
        LANGUAGES.put("xBase", "xBase");
        LANGUAGES.put("XC", "XC");
        LANGUAGES.put("XML", "XML");
        LANGUAGES.put("Xojo", "Xojo");
        LANGUAGES.put("XPages", "XPages");
        LANGUAGES.put("XProc", "XProc");
        LANGUAGES.put("XQuery", "XQuery");
        LANGUAGES.put("XS", "XS");
        LANGUAGES.put("XSLT", "XSLT");
        LANGUAGES.put("Xtend", "Xtend");
        LANGUAGES.put("Yacc", "Yacc");
        LANGUAGES.put("YAML", "YAML");
        LANGUAGES.put("YANG", "YANG");
        LANGUAGES.put("Zephir", "Zephir");
        LANGUAGES.put("Zimpl", "Zimpl");
    }
}
